language: node_js
sudo: required
dist: trusty
node_js: stable
services: mongodb
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-beta
cache:
  directories:
  - node_modules
before_script:
- mkdir -p ~/bin
- ln -s /usr/bin/google-chrome-beta ~/bin/google-chrome
- export PATH=$HOME/bin:$PATH
- npm install
- cp ./server/config/token.example.json ./server/config/token.json
- cp ./server/config/server.example.json ./server/config/server.json
script:
- npm test